// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartyPantz.Server.Models;

#nullable disable

namespace SmartyPantz.Server.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240801204131_activity")]
    partial class activity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartyPantz.Server.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chicka Chicka Boom Boom by Bill Martin Jr. and John Archambault",
                            SkillId = 1,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 2,
                            Name = "https://starfall.com",
                            SkillId = 1,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Endless Alphabet",
                            SkillId = 1,
                            Type = "App"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ABCmouse",
                            SkillId = 1,
                            Type = "App"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Counting Kisses by Karen Katz",
                            SkillId = 2,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 6,
                            Name = "https://mathplayground.com",
                            SkillId = 2,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 7,
                            Name = "https://ixl.com",
                            SkillId = 2,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Todo Math",
                            SkillId = 2,
                            Type = "App"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Count and Write Numbers",
                            SkillId = 2,
                            Type = "App"
                        },
                        new
                        {
                            Id = 10,
                            Name = "The Very Hungry Caterpillar by Eric Carle",
                            SkillId = 3,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 11,
                            Name = "https://pbskids.org",
                            SkillId = 3,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 12,
                            Name = "https://coolmath4kids.com",
                            SkillId = 3,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Count and Match",
                            SkillId = 3,
                            Type = "App"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Number Bingo",
                            SkillId = 3,
                            Type = "App"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Shapes by David A. Carter",
                            SkillId = 4,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 16,
                            Name = "https://abcmouse.com",
                            SkillId = 4,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 17,
                            Name = "https://kidsongs.com",
                            SkillId = 4,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Shapes & Colors by Intellijoy",
                            SkillId = 4,
                            Type = "App"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Kids Shapes",
                            SkillId = 4,
                            Type = "App"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Brown Bear, Brown Bear, What Do You See? by Bill Martin Jr. and Eric Carle",
                            SkillId = 5,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 21,
                            Name = "https://color-game.com",
                            SkillId = 5,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 22,
                            Name = "https://sesamestreet.org",
                            SkillId = 5,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Color Monster",
                            SkillId = 5,
                            Type = "App"
                        },
                        new
                        {
                            Id = 24,
                            Name = "My First Colors",
                            SkillId = 5,
                            Type = "App"
                        },
                        new
                        {
                            Id = 25,
                            Name = "The Busy Book by Trish Kuffner",
                            SkillId = 6,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 26,
                            Name = "https://funlearningforkids.com",
                            SkillId = 6,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 27,
                            Name = "https://playdoughtoplato.com",
                            SkillId = 6,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Fine Motor Fun",
                            SkillId = 6,
                            Type = "App"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Toca Boca Kitchen",
                            SkillId = 6,
                            Type = "App"
                        },
                        new
                        {
                            Id = 30,
                            Name = "The Name Jar by Yangsook Choi",
                            SkillId = 7,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 31,
                            Name = "https://name-tracing.com",
                            SkillId = 7,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 32,
                            Name = "https://starfall.com",
                            SkillId = 7,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Writing Wizard",
                            SkillId = 7,
                            Type = "App"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Tracing Letters & Numbers",
                            SkillId = 7,
                            Type = "App"
                        },
                        new
                        {
                            Id = 35,
                            Name = "If You Give a Mouse a Cookie by Laura Numeroff",
                            SkillId = 8,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 36,
                            Name = "https://kidsongs.com",
                            SkillId = 8,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 37,
                            Name = "https://abcmouse.com",
                            SkillId = 8,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 38,
                            Name = "The Family Book by Todd Parr",
                            SkillId = 9,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 39,
                            Name = "https://pbs.org/parents",
                            SkillId = 9,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 40,
                            Name = "https://k5learning.com",
                            SkillId = 9,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Llama Llama Time to Share by Anna Dewdney",
                            SkillId = 10,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 42,
                            Name = "https://childdevelopmentinfo.com",
                            SkillId = 10,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 43,
                            Name = "https://parenting.com",
                            SkillId = 10,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 44,
                            Name = "The Berenstain Bears Visit the Dentist by Stan & Jan Berenstain",
                            SkillId = 11,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 45,
                            Name = "https://supernanny.co.uk",
                            SkillId = 11,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 46,
                            Name = "https://positiveparenting.com",
                            SkillId = 11,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 47,
                            Name = "The Snowy Day by Ezra Jack Keats",
                            SkillId = 12,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 48,
                            Name = "https://readbrightly.com",
                            SkillId = 12,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 49,
                            Name = "https://literacytrust.org.uk",
                            SkillId = 12,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 50,
                            Name = "1, 2, 3 to the Zoo by Eric Carle",
                            SkillId = 13,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 51,
                            Name = "https://abcya.com",
                            SkillId = 13,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 52,
                            Name = "https://education.com",
                            SkillId = 13,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Dr. Seuss's ABC by Dr. Seuss",
                            SkillId = 14,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 54,
                            Name = "https://readingrockets.org",
                            SkillId = 14,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 55,
                            Name = "https://scholastic.com",
                            SkillId = 14,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Rosie’s Walk by Pat Hutchins",
                            SkillId = 15,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 57,
                            Name = "https://funbrain.com",
                            SkillId = 15,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 58,
                            Name = "https://tinkercad.com",
                            SkillId = 15,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 59,
                            Name = "From Head to Toe by Eric Carle",
                            SkillId = 16,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 60,
                            Name = "https://kidshealth.org",
                            SkillId = 16,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 61,
                            Name = "https://verywellfamily.com",
                            SkillId = 16,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 62,
                            Name = "The Berenstain Bears and the Trouble with Chores by Stan & Jan Berenstain",
                            SkillId = 17,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 63,
                            Name = "https://kidshealth.org",
                            SkillId = 17,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 64,
                            Name = "https://childrenshospital.org",
                            SkillId = 17,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 65,
                            Name = "What Time Is It, Mr. Crocodile? by Judy Sierra",
                            SkillId = 18,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 66,
                            Name = "https://time-for-kids.com",
                            SkillId = 18,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 67,
                            Name = "https://teachervision.com",
                            SkillId = 18,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Not a Box by Antoinette Portis",
                            SkillId = 19,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 69,
                            Name = "https://imaginativeplay.com",
                            SkillId = 19,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 70,
                            Name = "https://kidspot.com.au",
                            SkillId = 19,
                            Type = "Website"
                        });
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .HasColumnType("longtext");

                    b.Property<string>("ActivityDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activity = "Alphabet scavenger hunt",
                            ActivityDescription = "Find items around the house that start with each letter of the alphabet and practice writing the letters.",
                            Description = "Learn to recognize and write letters of the alphabet",
                            Title = "Alphabet Recognition and Writing"
                        },
                        new
                        {
                            Id = 2,
                            Activity = "Number matching game",
                            ActivityDescription = "Match number cards to groups of objects and practice writing the numbers.",
                            Description = "Learn to recognize and write numbers 1-20",
                            Title = "Number Recognition and Writing"
                        },
                        new
                        {
                            Id = 3,
                            Activity = "Counting jar",
                            ActivityDescription = "Fill a jar with small items and count them together.",
                            Description = "Learn to count objects up to 20",
                            Title = "Counting Objects"
                        },
                        new
                        {
                            Id = 4,
                            Activity = "Shape hunt",
                            ActivityDescription = "Find and identify shapes around the house or in nature.",
                            Description = "Learn to recognize basic shapes",
                            Title = "Shape Recognition"
                        },
                        new
                        {
                            Id = 5,
                            Activity = "Color sorting",
                            ActivityDescription = "Sort colored objects into different color groups and practice naming the colors.",
                            Description = "Learn to identify colors",
                            Title = "Color Identification"
                        },
                        new
                        {
                            Id = 6,
                            Activity = "Craft time with scissors",
                            ActivityDescription = "Cut out shapes from paper and create a simple craft.",
                            Description = "Develop fine motor skills through activities such as cutting with scissors, coloring, and tracing",
                            Title = "Fine Motor Skills Development"
                        },
                        new
                        {
                            Id = 7,
                            Activity = "Name practice sheets",
                            ActivityDescription = "Trace and write their name using practice sheets.",
                            Description = "Learn to recognize and write their own name",
                            Title = "Name Writing"
                        },
                        new
                        {
                            Id = 8,
                            Activity = "Simple recipe or craft",
                            ActivityDescription = "Follow a simple recipe or craft project with step-by-step instructions.",
                            Description = "Learn to follow simple instructions",
                            Title = "Following Instructions"
                        },
                        new
                        {
                            Id = 9,
                            Activity = "Playgroup games",
                            ActivityDescription = "Participate in group games or activities with friends or family.",
                            Description = "Learn to participate in group activities and share with others",
                            Title = "Group Participation"
                        },
                        new
                        {
                            Id = 10,
                            Activity = "Turn-taking games",
                            ActivityDescription = "Play games that require taking turns and listening to others.",
                            Description = "Develop basic social skills",
                            Title = "Social Skills"
                        },
                        new
                        {
                            Id = 11,
                            Activity = "Dressing practice",
                            ActivityDescription = "Practice dressing themselves with simple clothing items.",
                            Description = "Develop independence in tasks like dressing themselves and cleaning up after activities",
                            Title = "Independence in Tasks"
                        },
                        new
                        {
                            Id = 12,
                            Activity = "Read together",
                            ActivityDescription = "Read picture books and discuss the story to build vocabulary.",
                            Description = "Build vocabulary and language skills through reading and conversation",
                            Title = "Vocabulary and Language Skills"
                        },
                        new
                        {
                            Id = 13,
                            Activity = "Math games",
                            ActivityDescription = "Play simple addition and subtraction games using objects or drawings.",
                            Description = "Develop basic math skills such as understanding basic addition and subtraction concepts",
                            Title = "Basic Math Skills"
                        },
                        new
                        {
                            Id = 14,
                            Activity = "Rhyming games",
                            ActivityDescription = "Play rhyming games or read rhyming books to practice recognizing rhymes.",
                            Description = "Develop pre-reading skills such as recognizing rhyming words and understanding basic sight words",
                            Title = "Pre-Reading Skills"
                        },
                        new
                        {
                            Id = 15,
                            Activity = "Puzzle time",
                            ActivityDescription = "Work on age-appropriate puzzles to develop problem-solving skills.",
                            Description = "Develop basic problem-solving skills through puzzles and simple games",
                            Title = "Problem-Solving Skills"
                        },
                        new
                        {
                            Id = 16,
                            Activity = "Obstacle course",
                            ActivityDescription = "Create a simple obstacle course that includes running, jumping, and climbing.",
                            Description = "Develop gross motor skills through activities such as running, jumping, and climbing",
                            Title = "Gross Motor Skills"
                        },
                        new
                        {
                            Id = 17,
                            Activity = "Hygiene routine practice",
                            ActivityDescription = "Practice handwashing, brushing teeth, and covering coughs/sneezes with fun songs.",
                            Description = "Practice good hygiene habits such as washing hands and covering coughs/sneezes",
                            Title = "Hygiene Habits"
                        },
                        new
                        {
                            Id = 18,
                            Activity = "Daily schedule",
                            ActivityDescription = "Create a visual schedule with pictures to explain daily routines.",
                            Description = "Understand basic concepts of time such as morning, afternoon, and evening",
                            Title = "Understanding Time Concepts"
                        },
                        new
                        {
                            Id = 19,
                            Activity = "Dress-up and role play",
                            ActivityDescription = "Use costumes and props for imaginative play scenarios.",
                            Description = "Engage in imaginative play and creativity",
                            Title = "Imaginative Play and Creativity"
                        });
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.UserSkill", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<bool>("IsNeeded")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.Resource", b =>
                {
                    b.HasOne("SmartyPantz.Server.Models.Skill", "Skill")
                        .WithMany("Resource")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.UserProfile", b =>
                {
                    b.HasOne("SmartyPantz.Server.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("SmartyPantz.Server.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.UserSkill", b =>
                {
                    b.HasOne("SmartyPantz.Server.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartyPantz.Server.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartyPantz.Server.Models.UserProfile", null)
                        .WithMany("UserSkills")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.Skill", b =>
                {
                    b.Navigation("Resource");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.User", b =>
                {
                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.UserProfile", b =>
                {
                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
