// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartyPantz.Server.Models;

#nullable disable

namespace SmartyPantz.Server.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240725230534_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartyPantz.Server.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chicka Chicka Boom Boom by Bill Martin Jr. and John Archambault",
                            SkillId = 1,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 2,
                            Name = "https://starfall.com",
                            SkillId = 1,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Endless Alphabet",
                            SkillId = 1,
                            Type = "App"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ABCmouse",
                            SkillId = 1,
                            Type = "App"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Counting Kisses by Karen Katz",
                            SkillId = 2,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 6,
                            Name = "https://mathplayground.com",
                            SkillId = 2,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 7,
                            Name = "https://ixl.com",
                            SkillId = 2,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Todo Math",
                            SkillId = 2,
                            Type = "App"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Count and Write Numbers",
                            SkillId = 2,
                            Type = "App"
                        },
                        new
                        {
                            Id = 10,
                            Name = "The Very Hungry Caterpillar by Eric Carle",
                            SkillId = 3,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 11,
                            Name = "https://pbskids.org",
                            SkillId = 3,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 12,
                            Name = "https://coolmath4kids.com",
                            SkillId = 3,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Count and Match",
                            SkillId = 3,
                            Type = "App"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Number Bingo",
                            SkillId = 3,
                            Type = "App"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Shapes by David A. Carter",
                            SkillId = 4,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 16,
                            Name = "https://abcmouse.com",
                            SkillId = 4,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 17,
                            Name = "https://kidsongs.com",
                            SkillId = 4,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Shapes & Colors by Intellijoy",
                            SkillId = 4,
                            Type = "App"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Kids Shapes",
                            SkillId = 4,
                            Type = "App"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Brown Bear, Brown Bear, What Do You See? by Bill Martin Jr. and Eric Carle",
                            SkillId = 5,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 21,
                            Name = "https://color-game.com",
                            SkillId = 5,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 22,
                            Name = "https://sesamestreet.org",
                            SkillId = 5,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Color Monster",
                            SkillId = 5,
                            Type = "App"
                        },
                        new
                        {
                            Id = 24,
                            Name = "My First Colors",
                            SkillId = 5,
                            Type = "App"
                        },
                        new
                        {
                            Id = 25,
                            Name = "The Busy Book by Trish Kuffner",
                            SkillId = 6,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 26,
                            Name = "https://funlearningforkids.com",
                            SkillId = 6,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 27,
                            Name = "https://playdoughtoplato.com",
                            SkillId = 6,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Fine Motor Fun",
                            SkillId = 6,
                            Type = "App"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Toca Boca Kitchen",
                            SkillId = 6,
                            Type = "App"
                        },
                        new
                        {
                            Id = 30,
                            Name = "The Name Jar by Yangsook Choi",
                            SkillId = 7,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 31,
                            Name = "https://name-tracing.com",
                            SkillId = 7,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 32,
                            Name = "https://starfall.com",
                            SkillId = 7,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Writing Wizard",
                            SkillId = 7,
                            Type = "App"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Tracing Letters & Numbers",
                            SkillId = 7,
                            Type = "App"
                        },
                        new
                        {
                            Id = 35,
                            Name = "If You Give a Mouse a Cookie by Laura Numeroff",
                            SkillId = 8,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 36,
                            Name = "https://kidsongs.com",
                            SkillId = 8,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 37,
                            Name = "https://abcmouse.com",
                            SkillId = 8,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 38,
                            Name = "The Family Book by Todd Parr",
                            SkillId = 9,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 39,
                            Name = "https://pbs.org/parents",
                            SkillId = 9,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 40,
                            Name = "https://k5learning.com",
                            SkillId = 9,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Llama Llama Time to Share by Anna Dewdney",
                            SkillId = 10,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 42,
                            Name = "https://childdevelopmentinfo.com",
                            SkillId = 10,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 43,
                            Name = "https://parenting.com",
                            SkillId = 10,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 44,
                            Name = "The Berenstain Bears Visit the Dentist by Stan & Jan Berenstain",
                            SkillId = 11,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 45,
                            Name = "https://supernanny.co.uk",
                            SkillId = 11,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 46,
                            Name = "https://positiveparenting.com",
                            SkillId = 11,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 47,
                            Name = "The Snowy Day by Ezra Jack Keats",
                            SkillId = 12,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 48,
                            Name = "https://readbrightly.com",
                            SkillId = 12,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 49,
                            Name = "https://literacytrust.org.uk",
                            SkillId = 12,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 50,
                            Name = "1, 2, 3 to the Zoo by Eric Carle",
                            SkillId = 13,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 51,
                            Name = "https://abcya.com",
                            SkillId = 13,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 52,
                            Name = "https://education.com",
                            SkillId = 13,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Dr. Seuss's ABC by Dr. Seuss",
                            SkillId = 14,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 54,
                            Name = "https://readingrockets.org",
                            SkillId = 14,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 55,
                            Name = "https://scholastic.com",
                            SkillId = 14,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Rosie’s Walk by Pat Hutchins",
                            SkillId = 15,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 57,
                            Name = "https://funbrain.com",
                            SkillId = 15,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 58,
                            Name = "https://tinkercad.com",
                            SkillId = 15,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 59,
                            Name = "From Head to Toe by Eric Carle",
                            SkillId = 16,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 60,
                            Name = "https://kidshealth.org",
                            SkillId = 16,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 61,
                            Name = "https://verywellfamily.com",
                            SkillId = 16,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 62,
                            Name = "The Berenstain Bears and the Trouble with Chores by Stan & Jan Berenstain",
                            SkillId = 17,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 63,
                            Name = "https://kidshealth.org",
                            SkillId = 17,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 64,
                            Name = "https://childrenshospital.org",
                            SkillId = 17,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 65,
                            Name = "What Time Is It, Mr. Crocodile? by Judy Sierra",
                            SkillId = 18,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 66,
                            Name = "https://time-for-kids.com",
                            SkillId = 18,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 67,
                            Name = "https://teachervision.com",
                            SkillId = 18,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Not a Box by Antoinette Portis",
                            SkillId = 19,
                            Type = "Book"
                        },
                        new
                        {
                            Id = 69,
                            Name = "https://imaginativeplay.com",
                            SkillId = 19,
                            Type = "Website"
                        },
                        new
                        {
                            Id = 70,
                            Name = "https://kidspot.com.au",
                            SkillId = 19,
                            Type = "Website"
                        });
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Learn to recognize and write letters of the alphabet",
                            IsChecked = false,
                            Title = "Alphabet Recognition and Writing"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Learn to recognize and write numbers 1-20",
                            IsChecked = false,
                            Title = "Number Recognition and Writing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Learn to count objects up to 20",
                            IsChecked = false,
                            Title = "Counting Objects"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Learn to recognize basic shapes (circle, square, triangle, rectangle)",
                            IsChecked = false,
                            Title = "Shape Recognition"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Learn to identify colors",
                            IsChecked = false,
                            Title = "Color Identification"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Develop fine motor skills through activities such as cutting with scissors, coloring, and tracing",
                            IsChecked = false,
                            Title = "Fine Motor Skills Development"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Learn to recognize and write their own name",
                            IsChecked = false,
                            Title = "Name Writing"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Learn to follow simple instructions",
                            IsChecked = false,
                            Title = "Following Instructions"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Learn to participate in group activities and share with others",
                            IsChecked = false,
                            Title = "Group Participation"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Develop basic social skills such as taking turns and listening to others",
                            IsChecked = false,
                            Title = "Social Skills"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Develop independence in tasks like dressing themselves and cleaning up after activities",
                            IsChecked = false,
                            Title = "Independence in Tasks"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Build vocabulary and language skills through reading and conversation",
                            IsChecked = false,
                            Title = "Vocabulary and Language Skills"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Develop basic math skills such as understanding basic addition and subtraction concepts",
                            IsChecked = false,
                            Title = "Basic Math Skills"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Develop pre-reading skills such as recognizing rhyming words and understanding basic sight words",
                            IsChecked = false,
                            Title = "Pre-Reading Skills"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Develop basic problem-solving skills through puzzles and simple games",
                            IsChecked = false,
                            Title = "Problem-Solving Skills"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Develop gross motor skills through activities such as running, jumping, and climbing",
                            IsChecked = false,
                            Title = "Gross Motor Skills"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Practice good hygiene habits such as washing hands and covering coughs/sneezes",
                            IsChecked = false,
                            Title = "Hygiene Habits"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Understand basic concepts of time such as morning, afternoon, and evening",
                            IsChecked = false,
                            Title = "Understanding Time Concepts"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Engage in imaginative play and creativity",
                            IsChecked = false,
                            Title = "Imaginative Play and Creativity"
                        });
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildsAge")
                        .HasColumnType("int");

                    b.Property<string>("ChildsName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.Resource", b =>
                {
                    b.HasOne("SmartyPantz.Server.Models.Skill", "Skill")
                        .WithMany("Resource")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SmartyPantz.Server.Models.Skill", b =>
                {
                    b.Navigation("Resource");
                });
#pragma warning restore 612, 618
        }
    }
}
